package alert

import (
	"time"
)

// Level represents the severity of an alert.
type Level string

const (
	LevelInfo  Level = "info"
	LevelWarn  Level = "warn"
	LevelError Level = "error"
)

// Alert represents a single alert event generated by a state change.
type Alert struct {
	Host      string    `json:"host"`
	Port      int       `json:"port"`
	Level     Level     `json:"level"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
}

// New creates a new Alert.
func New(host string, port int, level Level, message string) Alert {
	return Alert{
		Host:      host,
		Port:      port,
		Level:     level,
		Message:   message,
		Timestamp: time.Now().UTC(),
	}
}

// String returns a human-readable representation of the alert.
func (a Alert) String() string {
	return a.Timestamp.Format(time.RFC3339) + " [" + string(a.Level) + "] " +
		a.Host + ":" + itoa(a.Port) + " - " + a.Message
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	buf := [20]byte{}
	pos := len(buf)
	for n > 0 {
		pos--
		buf[pos] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[pos:])
}
